apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qjp91aaqm-nodejs
  janus-idp.io/tekton: qjp91aaqm-nodejs
  backstage.io/kubernetes-id: qjp91aaqm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qjp91aaqm-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
