apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qjp91aaqm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qjp91aaqm-nodejs 
  name: qjp91aaqm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qjp91aaqm-nodejs 
